# Generated by Django 4.2.30 on 2026-05-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('thriller', 'Thriller')], max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('rating', models.FloatField(default=0.0)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
